import { Course } from '../types/types';
import css from '../../public/images/studyStudentPage/css.svg';
import coin from '../../public/images/studyStudentPage/coin.svg';

export const CourseStudent: Course[] = [
  {
    iconCss: css,
    iconCoin: coin,
    courseName: 'HTML/CSS',
    description: 'CourseStudent.description',
    lessons: 'CourseStudent.lessons',
    coins: 200,
    path: 'course/html&css',
    progress: 28,
    level: 'CourseStudent.level',
  },
  {
    iconCss: css,
    iconCoin: coin,
    courseName: 'JavaScript',
    description: 'CourseStudent.description',
    lessons: 'CourseStudent.lessons',
    coins: 200,
    path: 'course/javascript',
    progress: 28,
    level: 'CourseStudent.level',
  },
  {
    iconCss: css,
    iconCoin: coin,
    courseName: 'NodeJS',
    description: 'CourseStudent.description',
    lessons: 'CourseStudent.lessons',
    coins: 200,
    path: 'course/nodeJS',
    progress: 28,
    level: 'CourseStudent.level',
  },
  {
    iconCss: css,
    iconCoin: coin,
    courseName: 'ExpressJS',
    description: 'CourseStudent.description',
    lessons: 'CourseStudent.lessons',
    coins: 200,
    path: 'course/expressJS',
    progress: 28,
    level: 'CourseStudent.level',
  },
  {
    iconCss: css,
    iconCoin: coin,
    courseName: 'PosgreSQL',
    description: 'CourseStudent.description',
    lessons: 'CourseStudent.lessons',
    coins: 200,
    path: 'course/posgreSQL',
    progress: 28,
    level: 'CourseStudent.level',
  },
  {
    iconCss: css,
    iconCoin: coin,
    courseName: 'Docker',
    description: 'CourseStudent.description',
    lessons: 'CourseStudent.lessons',
    coins: 200,
    path: 'course/docker',
    progress: 28,
    level: 'CourseStudent.level',
  },
];
