import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles(() => ({
  navigation_container: {
    height: '92%',
    '@media (max-width: 1500px)': {
      height: '88%',
    },
  },
  navigation: {
    display: 'flex',
    height: '5%',
    marginLeft: '20px',
    width: '32%',
    alignItems: 'center',
    backgroundColor: '#2C2E34',
    borderRadius: '7px',
    '@media (max-width: 1500px)': {
      height: '7%',
      width: '32.3%',
    },
  },
  frame: {
    height: '100%',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '18px',
    lineHeight: '20px',
    letterSpacing: '0.03em',
    color: '#FFFFFF',
    textDecoration: 'none',
    padding: '0 5% 0 5%',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    background: 'none',
    border: 'none',
    '@media (max-width: 1500px)': {
      fontSize: '13px',
      padding: '0 4% 0 5%',
    },
  },
  active: {
    background: '#6B9AFF',
    boxShadow: '0px 0px 4px rgba(0, 0, 0, 0.25)',
    borderRadius: '7px',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '18px',
    lineHeight: '20px',
    letterSpacing: '0.03em',
    color: '#FFFFFF',
    height: '100%',
    padding: '0 5% 0 5%',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    border: 'none',
    '@media (max-width: 1500px)': {
      fontSize: '13px',
      padding: '0 4% 0 5%',
    },
  },
  course: {
    height: '28vh',
    margin: '20px 32px 0 20px',
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  routs: {
    all: 'unset',
    width: '32%',
    height: '130%',
    backgroundColor: '#2C2E34',
    borderRadius: '12px',
    paddingTop: '2%',
    marginBottom: '16px',
    '@media (max-width: 1500px)': {
      height: '125%',
      paddingTop: '1%',
    },
  },
  inside: {
    height: '95%',
    width: '90%',
    margin: 'auto',
  },
  title_image: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '50px',
    lineHeight: '47px',
    '@media (max-width: 1500px)': {
      fontSize: '30px',
    },
  },
  white_back: {
    width: '140px',
    height: '100px',
    backgroundColor: '#E9E9E9',
    borderRadius: '10px',
    textAlign: 'center',
    paddingTop: '2%',
    '@media (max-width: 1500px)': {
      width: '90px',
      height: '67px',
    },
  },
  icon: {
    width: '70%',
  },
  paragraf: {
    borderTop: '1px solid rgba(255, 255, 255, 0.3)',
    marginTop: '5%',
    height: '58%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingTop: '2%',
    '@media (max-width: 1500px)': {
      height: '55%',
      marginTop: '3%',
    },
  },
  description: {
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '20px',
    lineHeight: '131%',
    color: '#C6C6C6',
    '@media (max-width: 1500px)': {
      fontSize: '14px',
    },
  },
  info: {
    display: 'flex',
  },
  lessons: {
    width: '101px',
    height: '33px',
    background: '#41464A',
    borderRadius: '7px',
    textAlign: 'center',
    '@media (max-width: 1500px)': {
      width: '69px',
      height: '24px',
    },
  },
  coin: {
    marginLeft: '11px',
    display: 'flex',
    width: '82px',
    height: '33px',
    background: '#41464A',
    borderRadius: '7px',
    '@media (max-width: 1500px)': {
      width: '65px',
      height: '26px',
    },
  },
  coin_image: {
    height: '90%',
    margin: '1px 3px 0 3px',
  },
  info_title: {
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '21px',
    color: '#C6C6C6',
    paddingTop: '5%',
    '@media (max-width: 1500px)': {
      fontSize: '12px',
    },
  },
}));
